server:
  port: 28021
dubbo:
  application:
    name: dubbo-integration-provider
  protocol:
    port: ${DUBBO_PROTOCOL_PORT:28821}
    name: dubbo

spring:
  application:
    name: dubbo-integration-provider

feign:
  hystrix:
    enabled: true