server:
  port: 28820
dubbo:
  application:
    name: dubbo-integration-consumer
#  registry:
#    protocol: zookeeper
#    address: zookeeper://127.0.0.1:2181

spring:
  application:
    name: dubbo-integration-consumer

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000