name: "Common operations"
description: "do something common for all test"
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ env.javaVersion }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.javaVersion }}
        distribution: 'adopt'
        cache: maven
    - name: download zookeeper
      uses: actions/cache@v3
      with:
        path: apache-zookeeper-3.6.3-bin.tar.gz
        key: ${{ runner.os }}-apache-zookeeper-3.6.3
    - name: run zookeeper
      shell: bash
      run: |
        tar -zxf apache-zookeeper-3.6.3-bin.tar.gz
        bash apache-zookeeper-3.6.3-bin/bin/zkServer.sh start apache-zookeeper-3.6.3-bin/conf/zoo_sample.cfg
    - name: download local cse
      uses: actions/cache@v3
      with:
        path: Local-CSE-2.1.3-linux-amd64.zip
        key: ${{ runner.os }}-local-cse
        restore-keys: |
          ${{ runner.os }}-local-cse
    - name: start cse
      shell: bash
      run: |
        export ROOT_PATH=$(pwd)
        bash ./sermant-integration-tests/scripts/startCse.sh
    - name: download nacos server
      uses: actions/cache@v3
      with:
        path: nacos-server-1.4.2.tar.gz
        key: ${{ runner.os }}-nacos-server-1.4.2
        restore-keys: |
          ${{ runner.os }}-nacos-server-1.4.2
    - name: start nacos server
      shell: bash
      run: |
        tar -zxf nacos-server-1.4.2.tar.gz
        bash nacos/bin/startup.sh -m standalone
    - name: cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: download agent
      uses: actions/cache@v3
      with:
        path: sermant-agent-*/
        key: ${{ runner.os }}-agent-${{ github.run_id }}
    - name: plugin change check
      uses: ./.github/actions/common/plugin-change-check
    - name: change feign version
      shell: bash
      if: matrix.springCloudVersion != '2022.0.0' && matrix.springCloudVersion != '2022.0.1' && matrix.springCloudVersion != '2022.0.2'
      run: |
        sed -i 's/org.apache.httpcomponents/org.apache.httpcomponents.client5/' sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-api/pom.xml
        sed -i 's/httpclient/httpclient5/' sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-api/pom.xml
        sed -i 's/org.apache.http.conn/org.apache.hc.client5.http/' sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-api/src/main/java/com/huaweicloud/spring/feign/api/configuration/FeignClientSslConfigurationHighVersion.java.highVersion
    - name: change file version
      # For build feign client ssl call config, according to springCloud version discriminate high and low config.
      shell: bash
      run: |
        mv sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-api/src/main/java/com/huaweicloud/spring/feign/api/configuration/FeignClientSslConfigurationLowVersion.java sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-api/src/main/java/com/huaweicloud/spring/feign/api/configuration/FeignClientSslConfigurationLowVersion.java.lowVersion
        mv sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-api/src/main/java/com/huaweicloud/spring/feign/api/configuration/FeignClientSslConfigurationHighVersion.java.highVersion sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-api/src/main/java/com/huaweicloud/spring/feign/api/configuration/FeignClientSslConfigurationHighVersion.java
        ls sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-api/src/main/java/com/huaweicloud/spring/feign/api/configuration
        sed -i 's/qualifier/qualifiers/' sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-api/src/main/java/com/huaweicloud/spring/feign/api/FeignService.java
        sed -i 's/qualifier/qualifiers/' sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-api/src/main/java/com/huaweicloud/spring/feign/api/RemovalService.java
        sed -i 's/javax.servlet.http/jakarta.servlet.http/' sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign/feign-provider/src/main/java/com/huaweicloud/spring/feign/provider/FeignServiceImpl.java
        sed -i 's/javax.servlet.http/jakarta.servlet.http/' sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-provider/src/main/java/com/huaweicloud/spring/rest/provider/RouterController.java
        sed -i 's/javax.annotation/jakarta.annotation/' sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-consumer/src/main/java/com/huaweicloud/spring/rest/consumer/BootRegistryHttpClientController.java
        mv sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-consumer/src/main/java/com/huaweicloud/spring/rest/consumer/FlowcontrolConiguration.java sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-consumer/src/main/java/com/huaweicloud/spring/rest/consumer/FlowcontrolConiguration.java.spring
        mv sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-consumer/src/main/java/com/huaweicloud/spring/rest/consumer/FlowcontrolConiguration.java.springboot3 sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-consumer/src/main/java/com/huaweicloud/spring/rest/consumer/FlowcontrolConiguration.java