spring:
  application:
    name: spring-zuul

server:
  port: 8000

feign:
  hystrix:
    enabled: true

zuul:
  routes:
    rest-consumer: /rest/**
    feign-consumer: /feign/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000